# App stack: joins the base network, references base services by container name

networks:
  llm-net:
    external: true
    name: llm-net

services:

  interaction-platform:
    build: ./src/frontend
    image: homeserver:5000/llm-orchestration/frontend:latest
    container_name: interaction-platform
    ports:
      - "80:80"
    networks:
      - llm-net
    volumes:
      - ./src/starter:/app
    depends_on:
      orchestration-platform:
        condition: service_started

  orchestration-platform:
    build: ./src/scheduler
    image: homeserver:5000/llm-orchestration/scheduler:latest
    container_name: orchestration-platform
    networks:
      - llm-net
    group_add:
      - "998"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./hostData:/hostData
    environment:
      - HOST_PWD=${PWD}