# Correction Misplaced values
services:

  codebase:
    build: ./images/correction/misplaced/tier1/codebase
    image: homeserver:5000/llm-orchestration/correction_misplaced_tier1_codebase:latest
    container_name: codebase-correction-misplaced
    networks:
      - llm-net
    volumes:
      - ${INPUT}:/job/input.jsonl
      - ${OUTPUT}:/job/output.jsonl

networks:
  llm-net:
    external: true