# Correcting misspelled values
services:

  codebase:
    build: ./images/correction/misspelled/tier1/codebase
    container_name: codebase-correction-misspelled
    image: homeserver:5000/llm-orchestration/correction_misspelled_tier1_codebase:latest
    volumes:
      - ${INPUT}:/job/input.jsonl
      - ${OUTPUT}:/job/output.jsonl
