# Integration: Find duplication pairs
services:

  codebase:
    build: ./images/integration/duplicate_pairs/tier1/codebase
    container_name: codebase
    networks:
      - llm-net
    image: homeserver:5000/llm-orchestration/integration_duplicate_pairs_tier1_codebase:latest
    volumes:
      - ${INPUT}:/job/input.jsonl
      - ${OUTPUT}:/job/output.jsonl
      - /home/roman/code/llm-orchestration/data/statics/milvus/vector.db:/job/vector.db

networks:
  llm-net:
    external: true